account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    # path('login/', views.user_login, name='login'),

    # path('register/', views.UserRegister.as_view(), name='register'),

    path('profil/', views.profil, name='profil'),

    path('edit_profil/', views.edit_profil, name='edit_profil'),

    path('change_password/', views.change_password, name='change_password'),

    path('user_logout/', views.user_logout, name='user_logout'),
]

shop_product/urls.py
from django.urls import path
from . import views

app_name = "shop_product"


urlpatterns = [
    path('', views.ProductView.as_view(), name='home_page'),
   
    path('chekout/', views.ChekoutView.as_view(), name='chekout'),

    path('caregory/', views.categories_all, name='categories_all'),

    path('category/<int:pk>/', views.category_by_id, name='category_by_id'),

    path('brand/<int:pk>/', views.brand_by_id, name='brand'),

    path('product_detail/<slug:slug>/', views.ProductDetailView.as_view(), name='pro_detail'),

    path('my_cart/', views.MyCartView.as_view(), name='mycart'),

    path('add-to-cart/<int:pro_id>/', views.AddToCartView.as_view(), name='add_to_cart'),

    path('manager-cart/<int:cp_id>/', views.ManagerCartView.as_view(), name='manager'),

    path('all_delete/', views.AllDeleteView.as_view(), name='alldelete'),

    path('delete/<int:id>/', views.delete_product, name='delete_product'),

    path('product_edit/<int:pk>/', views.ProductEdit.as_view(), name='product_edit'),

    path('search/', views.search, name='search'),

    path('order_detail/<int:pk>/', views.UserOrderDetaile.as_view(), name='order_detail'),

    path('order/', views.orderview, name='myorder'),
]

shop_settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.views import  (LoginView, 
                                        LogoutView,
                                        PasswordResetView,
                                        PasswordResetDoneView,
                                        PasswordResetConfirmView,
                                        PasswordResetCompleteView)
from account.views import SignUpView
from shop_product.views import LandingPage




urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', LandingPage.as_view(), name="landing"),
    path('account/', include("account.urls")),
    path('shop/', include("shop_product.urls")),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('signup/', SignUpView.as_view(), name="signup"),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_product/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import translation

User = get_user_model()
from decimal import *
from PIL import Image
from io import BytesIO
from django.core.files import File
import string, random
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify
from django.conf import settings
from django.utils.translation import get_language


class Category(models.Model):
    name = models.CharField(max_length=250, null=True, blank=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


category_list = ['a', 'd', 'k', 'b', 'c', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'w', 'i', 'l', 'z']


@receiver(pre_save, sender=Category)
def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name + "_" + str(random.choice(category_list)))


class Brand(models.Model):
    name = models.CharField(max_length=250, null=True, blank=True)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey('Category', models.CASCADE)

    def __str__(self):
        return self.name


brand_list = ['a', 'd', 'k', 'b', 'c', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'w', 'i', 'l', 'z']


@receiver(pre_save, sender=Brand)
def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name + "_" + str(random.choice(brand_list)))


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, db_index=True)
    name_en = models.CharField(max_length=200, null=True, blank=True)
    name_ru = models.CharField(max_length=200, null=True, blank=True)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='shop_product/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField()
    rating = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    numReviews = models.IntegerField(default=0, null=True, blank=True)
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    warranty = models.CharField(max_length=250, null=True, blank=True)
    return_policy = models.CharField(max_length=250, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)
    countInstok = models.IntegerField(default=0, blank=True, null=True)
    createDat = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.image.closed:
            img = Image.open(self.image)
            img.thumbnail((500, 500), Image.ANTIALIAS)

            tmp = BytesIO()
            img.save(tmp, 'PNG')
            self.image = File(tmp, 'image.png')
        return super().save(*args, **kwargs)
    
    @property
    def name(self):
        column = 'name_{}'.format(get_language())
        return getattr(self, column)


str_list = ['a', 'd', 'k', 'b', 'c', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'w', 'i', 'l', 'z']


@receiver(pre_save, sender=Product)
def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name + "_" + str(random.choice(str_list)))


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    rating = models.IntegerField(default=0, blank=True, null=True)
    comment = models.TextField()

    def __str__(self):
        return str(self.rating)


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart" + str(self.id)

    def get_amount(self):
        return self.total * 100


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart" + str(self.cart_id) + "CartProduct" + str(self.id)


ORDER_STATUS = (
    ("Buyurtma qabul qilindi", "Buyurtma qabul qilindi"),
    ("Buyurtmani qayta ishlash", "Buyurtmani qayta ishlash"),
    ("Yo'lda", "Yo'lda"),
    ("Buyurtma bajarildi", "Buyurtma bajarildi"),
    ("Buyurtma bekor qilindi", "Buyurtma bekor qilindi")
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=250, null=True, blank=True)
    last_name = models.CharField(max_length=250, null=True, blank=True)
    city = models.CharField(max_length=200, blank=True, null=True, verbose_name="Shahar / Viloyat")
    district = models.CharField(max_length=200, blank=True, null=True, verbose_name="Tuman")
    street = models.CharField(max_length=200, blank=True, null=True, verbose_name="Ko'cha")
    house_number = models.IntegerField(blank=True, null=True, verbose_name="Uy nomeri")
    phone = models.CharField(max_length=14, verbose_name="Telefon Nomer")
    email = models.EmailField(null=True, blank=True, verbose_name="Elektron Pochta")
    discount = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=250, default=1, choices=ORDER_STATUS)
    createdAt = models.DateTimeField(auto_now_add=True)

shop_product/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, View, UpdateView, DetailView, TemplateView, CreateView
from .models import Category, Product, Brand, CartProduct, Cart, Order
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import OrderForm
from django.urls import reverse_lazy
from django.utils.translation import gettext as _


class LandingPage(TemplateView):
    template_name = "landing.html"


class ProductView(ListView):
    model = Product
    template_name = "shop_product/product.html"
    context_object_name = 'products'
    paginate_by = 4




class ProductDetailView(LoginRequiredMixin, TemplateView):
    template_name = "shop_product/product_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        url_slug = self.kwargs['slug']
        prod = Product.objects.get(slug=url_slug)
        prod.view_count += 1
        prod.save()
        context['product'] = prod
        return context


def categories_all(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {
        'categories': categories,
        "products": products,
    }
    return render(request, 'shop_product/categories.html', context)


def category_by_id(request, pk):
    category_f = Product.objects.filter(category_id=pk)
    brand_all = Brand.objects.filter(category=pk)
    context = {
        'category_f': category_f,
        'brand_all': brand_all,
    }
    return render(request, 'shop_product/category.html', context)




class AddToCartView(LoginRequiredMixin,View):
    def get(self, request, pro_id):
        product_id = pro_id
        # mahsulotni olish

        product_obj = Product.objects.get(id=product_id)
    #     # Maxsulot mavjudligini tekshirish
        cart_id = self.request.session.get('cart_id', None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            this_product_in_cart = cart_obj.cartproduct_set.filter(product=product_obj)
            if this_product_in_cart.exists():
                cartproduct = this_product_in_cart.last()
                cartproduct.quantity += 1
                cartproduct.subtotal += product_obj.selling_price
                cartproduct.save()
                cart_obj.total += product_obj.selling_price
                cart_obj.save()
            else:
                cartproduct = CartProduct.objects.create(cart=cart_obj, product=product_obj, rate=product_obj.selling_price,
                                                         quantity=1, subtotal=product_obj.selling_price)

                cart_obj.total += product_obj.selling_price
                cart_obj.save()
        else:
            cart_obj = Cart.objects.create(user=self.request.user, total=0)
            self.request.session['cart_id'] = cart_obj.id
            cartproduct = CartProduct.objects.create(cart=cart_obj, product=product_obj,
                                                     rate=product_obj.selling_price, subtotal=product_obj.selling_price, quantity=1)
            cart_obj.total += product_obj.selling_price
            cart_obj.save()

        # messages.info(request, "This item was added to your cart.")
        return redirect('shop_product:mycart')



class MyCartView(TemplateView):
    template_name = "shop_product/cart.html"
    def get_context_data(self, **kwargs):
        context = super(MyCartView, self).get_context_data(**kwargs)
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cartt = Cart.objects.get(id=cart_id)
        else:
            cartt = None
        context['cartt'] = cartt
        return context


class ManagerCartView(View):
    def get(self, request, *args, **kwargs):
        cp_id = self.kwargs['cp_id']
        action = request.GET.get('action')
        cp_obj = CartProduct.objects.get(id=cp_id)
        cart_obj = cp_obj.cart
        if action == "inc":
            cp_obj.quantity += 1
            cp_obj.subtotal += cp_obj.rate
            cp_obj.save()
            cart_obj.total += cp_obj.rate
            # messages.info(request, "This item quantity was updated.")
            cart_obj.save()
        elif action == "dcr":
            cp_obj.quantity -= 1
            cp_obj.subtotal -= cp_obj.rate
            cp_obj.save()
            cart_obj.total -= cp_obj.rate
            # messages.info(request, "This item was removed from your cart.")
            cart_obj.save()
            if cp_obj.quantity == 0:
                cp_obj.delete()
        elif action == "rmv":
            cart_obj.total -= cp_obj.subtotal
            cart_obj.save()
            cp_obj.delete()
            # messages.info(request, "This item was deleted from your cart.")
        return redirect('shop_product:mycart')



class AllDeleteView(View):
    def get(self, request, *args, **kwargs):
        cart_id = request.session.get('cart_id', None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
            cart.cartproduct_set.all().delete()
            cart.total = 0
            cart.save()
            # messages.info(request, "This items was cleaned from your cart.")
        return redirect('shop_product:mycart')


class ProductEdit(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    template_name = "shop_product/product_edit.html"
    success_url = "/"
    fields = '__all__'

    def test_func(self):
        obj = self.get_object()
        return self.request.user.is_superuser or obj.user == self.request.user


class ChekoutView(CreateView):
    template_name = 'shop_product/chekout.html'
    form_class = OrderForm
    success_url = reverse_lazy("shop_product:myorder")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
        else:
            cart_obj = None
        context['cart'] = cart_obj
        return context

    def form_valid(self, form):
        cart_id = self.request.session.get("cart_id")
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            user = self.request.user
            form.instance.user = user
            form.instance.cart = cart_obj
            form.instance.subtotal = cart_obj.total
            form.instance.discount = 0
            form.instance.total = cart_obj.total
            form.instance.order_status = "Buyurtma qabul qilindi"
            del self.request.session['cart_id']
        else:
            return redirect('shop_product:myorder')
        return super().form_valid(form)


"""
<< Delete product >>
"""
def delete_product(request, id):
    products = Product.objects.get(pk=id)
    products.delete()
    # messages.info(request, "Product ochirildi.")
    return redirect('shop_product:home_page')



def search(request):
    if request.method == "POST":
        searched = request.POST['searched']
        products = Product.objects.filter(name_en__icontains=searched)
        context = {
            'searched': searched,
            'products': products,
        }
        
        return render(request, "shop_product/search.html", context)
    else:
        return render(request, "shop_product/search.html")



def brand_by_id(request, pk):
    brand_f = Product.objects.filter(brand_id=pk)
    
    context = {
        'brand_f': brand_f,
        
    }
    return render(request, "shop_product/brand.html", context)





class UserOrderDetaile(DetailView):
    template_name = 'shop_product/order_detail.html'
    model = Order
    context_object_name = "ord_obj"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            pass
        else:
            return redirect('account:login')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserOrderDetaile, self).get_context_data(**kwargs)
        context['products'] = Product.objects.all()
        return context


def orderview(request):
    users = request.user
    orders = Order.objects.filter(user=users)
    context = {
        "orders": orders
    }
    return render(request, 'shop_product/order.html', context)

shop_product/templates/shop_product/brand.html
{% extends 'layout.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <section class="banner_area">
        <div class="banner_inner d-flex align-items-center">
            <div class="container">
                <div class="banner_content text-center">
                    <h2>Shop Category Page</h2>
                    <div class="page_link">
                        <a href="{% url 'shop_product:home_page' %}">{% trans 'Home' %}</a>
                        <a href="{% url 'shop_product:categories_all' %}">{% trans 'Category' %}</a>
                        <a href="category.html">{% trans 'Brand' %}</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="cat_product_area p_120">
        <div class="container">
            <div class="row flex-row-reverse">
                <div class="col-lg-9">
                    <div class="product_top_bar">
                        <div class="left_dorp">
                            <select class="sorting">
                                <option value="1">Default sorting</option>
                                <option value="2">Default sorting 01</option>
                                <option value="4">Default sorting 02</option>
                            </select>
                            <select class="show">
                                <option value="1">Show 12</option>
                                <option value="2">Show 14</option>
                                <option value="4">Show 16</option>
                            </select>
                        </div>
                        <div class="right_page ml-auto">
                            <nav class="cat_page" aria-label="Page navigation example">
                                <ul class="pagination">
                                    <li class="page-item"><a class="page-link" href="#"><i class="fa fa-long-arrow-left"
                                                                                           aria-hidden="true"></i></a>
                                    </li>
                                    <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                                    <li class="page-item blank"><a class="page-link" href="#">...</a></li>
                                    <li class="page-item"><a class="page-link" href="#">6</a></li>
                                    <li class="page-item"><a class="page-link" href="#"><i
                                            class="fa fa-long-arrow-right" aria-hidden="true"></i></a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="latest_product_inner row">
                        {% for product in brand_f %}
                        <div class="col-lg-4 col-md-4 col-sm-6">
                            
                            <div class="f_p_item">
                                
                                <div class="f_p_img">
                                    <img class="img-fluid" src="{{ product.image.url }}"
                                         alt="">
                                    <div class="p_icon">
                                        
                                        <a href="{% url 'shop_product:pro_detail' product.slug %}"><i class="lnr lnr-cart"></i></a>
                                    </div>
                                </div>
                                
                                <a href="{% url 'shop_product:pro_detail' product.slug %}"><h4>{{ product.name }}</h4></a>
                                <h5>{{product.selling_price}} $</h5>
                                <i class="
                                            {% if product.rating < 0.5 %}far fa-star {% elif product.rating == 0.5 %} fa fa-star-half-alt {% else %} fa fa-star {% endif %} "
                                       aria-hidden="true" style="color: yellow"></i>
                                    <i class="
                                             {% if product.rating < 1.5 %}far fa-star {% elif product.rating == 1.5 %}fa fa-star-half-alt {% else %} fa fa-star{% endif %} "
                                       aria-hidden="true" style="color: yellow"></i>
                                    <i class="
                                            {% if product.rating < 2.5 %}far fa-star{% elif product.rating == 2.5 %}fa fa-star-half-alt {% else %} fa fa-star{% endif %} "
                                       aria-hidden="true" style="color: yellow"></i>
                                    <i class="
                                             {% if product.rating < 3.5 %}far fa-star{% elif product.rating == 3.5 %}fa fa-star-half-alt {% else %} fa fa-star{% endif %} "
                                       aria-hidden="true" style="color: yellow">
                                </i>
                                <br/>
                                <div class="mt-2">
                                {% if user.is_authenticated and product.user_id == user.id or user.is_staff %}
                                        <a class="btn bg-primary text-white"
                                           href="{% url 'shop_product:product_edit' product.id %}"><small><i>{% trans 'Edit' %}</i></small></a>
                                    {% endif %}

                                    {% if user.is_authenticated and product.user_id == user.id or user.is_staff %}
                                        <a class="btn bg-danger text-white ml-1"
                                           href="{% url 'shop_product:delete_product' product.id %}"><small><i>{% trans 'Delete' %}</i></small></a>
                                    {% endif %}
                                    </div>

                           
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="left_sidebar_area">
                        <aside class="left_widgets p_filter_widgets">
                            <div class="l_w_title">
                                <h3>{% trans 'Product Filters' %}</h3>
                            </div>
                          


                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

shop_product/templates/shop_product/chekout.html
{% extends 'layout.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <section class="banner_area">
        <div class="banner_inner d-flex align-items-center">
            <div class="container">
                <div class="banner_content text-center">
                    <h2>Product Checkout</h2>
                    <div class="page_link">
                        <a href="{% url 'shop_product:home_page' %}">Home</a>
                        <a href="checkout.html">Checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="checkout_area p_120">
        <div class="container">
            <div class="billing_details">
                <div class="row">
                    <div class="col-lg-8">
                        <h3>{% trans 'Billing Details' %}</h3>
                        <form class="row contact_form" action="{% url 'shop_product:chekout' %}" method="post" novalidate="novalidate">
                            {% csrf_token%}
                            <div class="col-md-6 form-group p_star">
                                <input type="text" class="form-control" id="id_first_name" name="first_name" placeholder="First name">
                            </div>
                            <div class="col-md-6 form-group p_star">
                                <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="Last name">
                              
                            </div>
                            
                            <div class="col-md-6 form-group p_star">
                                <input type="text" class="form-control" id="id_phone" name="phone" placeholder="Phone number">
                               
                            </div>
                            <div class="col-md-6 form-group p_star">
                                <input type="text" class="form-control" id="id_email" name="email" placeholder="Email Address">
                                
                            </div>
                           
                            
                            
                            <div class="col-md-12 form-group p_star">
                                <input type="text" class="form-control" id="id_city" name="city" placeholder="Town/City">
                               
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <input type="text" class="form-control" id="id_district" name="district" placeholder="District">
                        
                            </div>
                            <!-- <div class="col-md-12 form-group">
                                <input type="text" class="form-control" id="zip" name="zip" placeholder="Postcode/ZIP">
                            </div> -->
                            <div class="col-md-12 form-group p_star">
                                <input type="text" class="form-control" id="id_house_number" name="house_number" placeholder="Address line 01">
                  
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <input type="text" class="form-control" id="id_street" name="street" placeholder="Street">
                                
                            </div>
                            <button class="main_btn" type="submit">{% trans 'Proceed to Apelsin' %}</button>
                          
                        </form>
                    </div>
                    <div class="col-lg-4">
                        <div class="order_box">
                            <h2>{% trans 'Your Order' %}</h2>
                            {% for rt in cart.cartproduct_set.all %}
                            <ul class="list">
                                <li><a href="#">Product <span>Total</span></a></li>
                                <li><a href="#">{{ rt.product.name }}  <span class="middle">x {{rt.quantity}}</span> <span class="last">${{ rt.subtotal }}</span></a>
                                </li>
                                
                            </ul>
                            {% endfor %}
                            <ul class="list list_2">
                               
                                <li><a href="#">Total <span>{{ cart.total }}</span></a></li>
                            </ul>
                            
                            <div class="payment_item">
                                <div class="radion_btn">
                                    <input type="radio" id="f-option5" name="selector">
                                    <label for="f-option5">{% trans 'Check payments' %}</label>
                                    <div class="check"></div>
                                </div>
                                <p>Please send a check to Store Name, Store Street, Store Town, Store State / County,
                                    Store Postcode</p>
                            </div>
                            
                            <div class="creat_account">
                                <input type="checkbox" id="f-option4" name="selector">
                                <label for="f-option4">{% trans 'I’ve read and accept the' %} </label>
                                <a href="#">terms & conditions*</a>
                            </div>
                            <a class="main_btn" href="{% url 'shop_product:mycart' %}">{% trans 'Continuie shopping' %}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

shop_product/templates/shop_product/product_edit.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}



{% block content %}
    <section class="order_details section-margin--small">
        <div class="container">
            <p class="text-center billing-alert"></p>
            <div class="row mb-5">
                <div class="order_details_table">
                    <h2>{% trans 'Product Edit' %}</h2>
                    <div class="table-responsive">
                        <table class="table">
                            <form action="{% url 'shop_product:product_edit' object.id %}" method="POST"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form | crispy }}
                                <img src="{{ object.image.url }}" alt="rasm" class="img-responsive">
                                <br/>
                                <button type="submit" class="btn btn-primary mt-3">{% trans 'Edit' %}</button>
                            </form>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}