account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    # path('login/', views.user_login, name='login'),

    # path('register/', views.UserRegister.as_view(), name='register'),

    path('profil/', views.profil, name='profil'),

    path('edit_profil/', views.edit_profil, name='edit_profil'),

    path('change_password/', views.change_password, name='change_password'),

    path('user_logout/', views.user_logout, name='user_logout'),
]

shop_product/urls.py
from django.urls import path
from . import views

app_name = "shop_product"


urlpatterns = [
    path('', views.ProductView.as_view(), name='home_page'),
   
    path('chekout/', views.ChekoutView.as_view(), name='chekout'),

    path('caregory/', views.categories_all, name='categories_all'),

    path('category/<int:pk>/', views.category_by_id, name='category_by_id'),

    path('brand/<int:pk>/', views.brand_by_id, name='brand'),

    path('product_detail/<slug:slug>/', views.ProductDetailView.as_view(), name='pro_detail'),

    path('my_cart/', views.MyCartView.as_view(), name='mycart'),

    path('add-to-cart/<int:pro_id>/', views.AddToCartView.as_view(), name='add_to_cart'),

    path('manager-cart/<int:cp_id>/', views.ManagerCartView.as_view(), name='manager'),

    path('all_delete/', views.AllDeleteView.as_view(), name='alldelete'),

    path('delete/<int:id>/', views.delete_product, name='delete_product'),

    path('product_edit/<int:pk>/', views.ProductEdit.as_view(), name='product_edit'),

    path('search/', views.search, name='search'),

    path('order_detail/<int:pk>/', views.UserOrderDetaile.as_view(), name='order_detail'),

    path('order/', views.orderview, name='myorder'),
]

shop_settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.views import  (LoginView, 
                                        LogoutView,
                                        PasswordResetView,
                                        PasswordResetDoneView,
                                        PasswordResetConfirmView,
                                        PasswordResetCompleteView)
from account.views import SignUpView
from shop_product.views import LandingPage




urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', LandingPage.as_view(), name="landing"),
    path('account/', include("account.urls")),
    path('shop/', include("shop_product.urls")),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('signup/', SignUpView.as_view(), name="signup"),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/landing.html
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png">
    <title>New</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min..css' %}">
    <link rel="stylesheet" href="{% static 'account/linericon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'account/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'account/lightbox/simpleLightbox.css' %}">
    <link rel="stylesheet" href="{% static 'account/nice-select/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'account/animate-css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'account/jquery-ui/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/proo.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link rel="stylesheet" href="{% static 'css/css_t/styles.css' %}">
</head>
<body>

<header class="header_area">

    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light main_box">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <a class="navbar-brand logo_h" href="{% url 'shop_product:home_page' %}"><img
                        src="{% static 'img/logo.png' %}" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto">
                        
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                            aria-haspopup="true" aria-expanded="false">{% trans 'Languages' %}</a>
                             <ul class="dropdown-menu">

                                <li class="nav-item"><a class="nav-link" href="/en/">en</a>
                                <li class="nav-item"><a class="nav-link" href="/ru/">ru</a>
                                      
                                

                            </ul>
                           
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">{% trans 'Login' %}</a>
                        <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">{% trans 'Register' %}</a>

                        
                    
                </div>
            </div>
        </nav>
    </div>
</header>




<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{% static 'img/dashboard.svg' %}">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            New to our website?
        </h1>
        <p class="mb-8 leading-relaxed">
            Welcom to online shop
        </p>
        <div class="flex justify-center">
          <a href="{% url 'login' %}" class="inline-flex text-white main_btn border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded text-lg">
            Login to get started
          </a>
        </div>
      </div>
    </div>
</section>

templates/layout.html
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png">
    <title>New</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min..css' %}">
    <link rel="stylesheet" href="{% static 'account/linericon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'account/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'account/lightbox/simpleLightbox.css' %}">
    <link rel="stylesheet" href="{% static 'account/nice-select/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'account/animate-css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'account/jquery-ui/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/proo.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>
<body>


<header class="header_area">
    <div class="top_menu row m0">
        <div class="container">
            <div class="float-left">
                <a href="mailto:support@colorlib.com">support@colorlib.com</a>
                <a href="#">{% trans "Welcome to Catalouge" %}</a>
            </div>
            <div class="float-right">
                <ul class="header_social">
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                    <li><a href="#"><i class="fa fa-behance"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light main_box">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <a class="navbar-brand logo_h" href="{% url 'shop_product:home_page' %}"><img
                        src="{% static 'img/logo.png' %}" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto">
                        
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                            aria-haspopup="true" aria-expanded="false">{% trans 'Languages' %}</a>
                             <ul class="dropdown-menu">

                                <li class="nav-item"><a class="nav-link" href="/en/">en</a>
                                <li class="nav-item"><a class="nav-link" href="/ru/">ru</a>
                                      
                                

                            </ul>
                           
                        </li>
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">{% trans 'Shop' %}</a>
                            <ul class="dropdown-menu">

                                <li class="nav-item"><a class="nav-link" href="{% url 'shop_product:categories_all' %}">{% trans 'Shop Category' %}</a>
                               
                                <li class="nav-item"><a class="nav-link" href="{% url 'shop_product:chekout' %}">{% trans 'Product Checkout' %}</a>
                                <li class="nav-item"><a class="nav-link" href="{% url 'shop_product:myorder' %}">{% trans 'Confirmation' %}</a></li>
                                
                                

                            </ul>
                        </li>
                        <li class="nav-item submenu dropdown">
                            <a class="d-flex align-items-center nav-link dropdown-toggle dropdown-toggle-nocaret"
                           href="{% url 'account:profil' %}"
                           role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           {% if user.is_authenticated %}
                            <img src="{{ user.image.url }}" class="user-img"
                                 alt="" />
                                 {% else %}
                                 Profile
                                 {%endif%}

                            <div class="user-info ps-3">
                                <p class="user-name mb-0">{{ user.username }}</p>
                                <p class="designattion mb-0"></p>
                            </div>
                            </a>
                            <ul class="dropdown-menu">
                                {% if user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'account:user_logout' %}">{% trans 'Logout' %}</a></li>
                                {% else %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">{% trans 'Login' %}</a>
                                <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">{% trans 'Register' %}</a>
                                {% endif %}
                            </ul>
                        </li>

                        <!-- <li class="nav-item"><a class="nav-link" href="{% url 'account:profil' %}">{{ user.username }}</a></li> -->
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item"><a href="{% url 'shop_product:mycart' %}" class="cart"><i class="lnr lnr lnr-cart"></i></a></li>
                        <li class="nav-item">
                            <form class="mt-4" action="{% url 'shop_product:search' %}" method=POST
                            class="input-group filter-bar-search ">
                              {% csrf_token %}
                                <input type="text" placeholder="Search" name="searched">
                               
                            </form>
                            
                        </li>
                        

                    </ul>
                </div>
            </div>
        </nav>
    </div>
</header>

{% block content %}{% endblock %}

<footer class="footer-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6 class="footer_title">About Us</h6>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore dolore magna aliqua.</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6 class="footer_title">Newsletter</h6>
                    <p>Stay updated with our latest trends</p>
                    <div id="mc_embed_signup">
                        <form target="_blank"
                              action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                              method="get" class="subscribe_form relative">
                            <div class="input-group d-flex flex-row">
                                <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''"
                                       onblur="this.placeholder = 'Email Address '" required="" type="email">
                                <button class="btn sub-btn"><span class="lnr lnr-arrow-right"></span></button>
                            </div>
                            <div class="mt-10 info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget instafeed">
                    <h6 class="footer_title">Instagram Feed</h6>
                    <ul class="list instafeed d-flex flex-wrap">
                        <li><img src="{% static 'img/instagram/Image-01.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/instagram/Image-02.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/instagram/Image-03.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/instagram/Image-04.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/instagram/Image-05.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/instagram/Image-06.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/instagram/Image-07.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/instagram/Image-08.jpg' %}" alt=""></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="single-footer-widget f_social_wd">
                    <h6 class="footer_title">Follow Us</h6>
                    <p>Let us be social</p>
                    <div class="f_social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>


<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/stellar.js' %}"></script>
<script src="{% static 'account/lightbox/simpleLightbox.min.js' %}"></script>
<script src="{% static 'account/nice-select/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'account/isotope/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'account/isotope/isotope-min.js' %}"></script>
<script src="{% static 'account/owl-carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'account/counter-up/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'account/flipclock/timer.js' %}"></script>
<script src="{% static 'account/counter-up/jquery.counterup.js' %}"></script>
<script src="{% static 'js/mail-script.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>
</body>
</html>